### ISSUE TITLE
Icon/Logo Proposal

### ISSUE THREAD

**Issue by loydjayme25** [ardovic/Currency-Rates-Viewer#1]
Good day PO, i would love to submit my design for your project.

**Comment by loydjayme25** [comment]
And here's my design for your project sir.

![proposals](https://user-images.githubusercontent.com/37318022/40266123-1389c328-5b78-11e8-8f7d-74b4fbf3aec4.png)

**Comment by ardovic** [comment]
Great, you can make a pull request with the logo inside a folder in root.

**Comment by loydjayme25** [comment]
okay sir, i will send a PR.

**Comment by loydjayme25** [comment]
PR already sent sir, i am honored to contribute on your project.

**Comment by ardovic** [comment]
Well done!
